# Generated by Django 5.1.4 on 2025-07-14 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Matricule')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('fac', models.CharField(choices=[('Sciences Informatiques', 'informatique'), ('Sciences Biomédicales', 'medecine'), ('Sciences Juridiques', 'droit'), ('Sciences Sociales', 'social'), ('Sciences Economiques', 'economie'), ('Sciences Agronomiques', 'agronomie'), ('Ecole de Santé Publique', 'sante'), ('Sciences Psychologiques', 'psycho'), ("Sciences de l'Information et de la Communication", 'sic')], max_length=255, verbose_name='Faculté')),
                ('prom', models.CharField(choices=[('Bac+1', 'bac1'), ('Bac+2', 'bac2'), ('Bac+3', 'bac3')], max_length=255)),
                ('description', models.TextField()),
                ('num_candidat', models.IntegerField()),
                ('poste', models.CharField(choices=[('coordo', 'Coordonnateur des Etudiants'), ('vice-cordo', 'Vice-Coordonnateur des Etudiants'), ('sec', 'Sécretaire de la Coordination'), ('tresorier', 'Trésorier de la Coordination'), ('cc', 'Chargé de Communication de la Coordination')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('detail', models.TextField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('fac', models.CharField(choices=[('Sciences Informatiques', 'informatique'), ('Sciences Biomédicales', 'medecine'), ('Sciences Juridiques', 'droit'), ('Sciences Sociales', 'social'), ('Sciences Economiques', 'economie'), ('Sciences Agronomiques', 'agronomie'), ('Ecole de Santé Publique', 'sante'), ('Sciences Psychologiques', 'psycho'), ("Sciences de l'Information et de la Communication", 'sic')], max_length=255, verbose_name='Faculté')),
                ('prom', models.CharField(choices=[('Bac+1', 'bac1'), ('Bac+2', 'bac2'), ('Bac+3', 'bac3')], max_length=255, verbose_name='Promotion')),
                ('voted', models.BooleanField(default=False)),
                ('candidat', models.ManyToManyField(blank=True, null=True, related_name='votant', to='Appli_vote.candidat')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli_vote.election')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli_vote.election'),
        ),
    ]
