# Generated by Django 5.1.4 on 2025-01-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-pk'], 'verbose_name': 'Election'},
        ),
        migrations.AddField(
            model_name='candidat',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='election',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli_vote.election'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prom',
            field=models.CharField(choices=[('G1', 'g1'), ('G2', 'g2'), ('G3', 'g3'), ('L1', 'l1'), ('L2', 'l2'), ('Bac+1', 'bac1'), ('Bac+2', 'bac2'), ('Bac+3', 'bac3')], max_length=255),
        ),
        migrations.AlterField(
            model_name='electeur',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Appli_vote.election'),
        ),
        migrations.AlterField(
            model_name='electeur',
            name='prom',
            field=models.CharField(choices=[('G1', 'g1'), ('G2', 'g2'), ('G3', 'g3'), ('L1', 'l1'), ('L2', 'l2'), ('Bac+1', 'bac1'), ('Bac+2', 'bac2'), ('Bac+3', 'bac3')], max_length=255, verbose_name='Promotion'),
        ),
    ]
