# Generated by Django 5.1.4 on 2025-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_vote', '0002_alter_election_options_candidat_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
