# Generated by Django 5.1.4 on 2025-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_vote', '0003_alter_candidat_description_alter_election_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
