# Generated by Django 5.1.6 on 2025-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli_vote', '0004_alter_candidat_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='description',
            field=models.TextField(blank=True, default='Aucune description', null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
